### ISSUE TITLE
PHP Fatal error:  Interface 'Magento\\Framework\\Object\\IdentityInterface' not found

### ISSUE THREAD

**Issue by comunidademagento** [ashsmith/ashsmithio#1]
Hello Ash Smith,

See images below.

Presented white screen when try access this link.

http://127.0.0.1/public_html/magento2-1.0.0-beta-dev05/magento2/blog

With command tail -f /var/log/apache2/error.log return this message ...

PHP Fatal error:  Interface 'Magento\\Framework\\Object\\IdentityInterface' not found in /home/magento2ubuntu1404/dados/public_html/magento2-1.0.0-beta-dev05/magento2/app/code/Ashsmith/Blog/Block/PostList.php on line 9

![captura de tela de 2015-09-01 22 10 33](https://cloud.githubusercontent.com/assets/7476455/9620971/49940192-50f7-11e5-91ab-f2105cafc5c6.png)

![captura de tela de 2015-09-01 22 10 44](https://cloud.githubusercontent.com/assets/7476455/9620972/49bea12c-50f7-11e5-9c1c-8aec882c28f1.png)

**Comment by ashsmith** [comment]
This was an issue between versions of Magento 2, they changed the naming of multiple interfaces which caught me out. This has been updated and resolved.
