### ISSUE TITLE
Rewrite CSS

### ISSUE THREAD

**Issue by ashsmith** [ashsmith/ashsmithio#21]
I like how the site looks, so generally speaking no visual changes should be made.

However, the CSS sucks. I'm no frontend dev, but that is not an excuse to slack off. It's a complete mess, so I think stripping it and rebuilding will be the best option.

**Comment by bobbypinard** [comment]
Can I work on doing that?

**Comment by ashsmith** [comment]
Thanks for the offer, but I've got this covered :)
