### ISSUE TITLE
Atom feed points to localhost:4000

### ISSUE THREAD

**Issue by hostep** [ashsmith/ashsmithio#22]
Hi @ashsmith 

Been trying to follow your blog in my RSS reader.
But there is something wrong with the url's in your feed: https://www.ashsmith.io/feed.xml
They all point to `http://localhost:4000/`

Would be nice if this could get fixed.

Thanks and keep on writing great articles! :)

**Comment by ashsmith** [comment]
Well that's embarrassing! Thank you for reporting.

I have fixed the issue now, once CloudFront's caches have expired then the feed will be fixed

Thanks!

**Comment by hostep** [comment]
I can confirm it is working now, thanks for the quick fix! :)
