### ISSUE TITLE
magento observers

### ISSUE THREAD

**Issue by ahnbizcad** [ashsmith/ashsmithio#8]
how does the $observer parameter get set?
do you not pass it anything?
Does the Mage code somewhere automatically pass in the observer object when triggering an observer function?

I've seen `$observer->getEvent()`;

How do you pass data into an observer function? I've seen  observer methods with data array argument passed in.

**Comment by ashsmith** [comment]
Good question, sorry for the delay.

Events are dispatched in Magento 1.x via `Mage::dispatchEvent('your_event_name', array('somedatakey' => 'somedata));`

The second parameter (the array), is where data is passed into the observer.
